services:
  backend:
    image: crm-backend-dev:1.0.0
    build: ./Service/Backend
    env_file:
      - .env.backend
    environment:
      MODE: Development
      API_URL: ${DEV_URL}:${FRONTEND_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./Service/Backend/src:/app/src
      - ./Log:/logs
    depends_on:
      - mongo
    restart: always
    ports:
      - ${BACKEND_PORT}:5000

  mongo:
    image: mongo:7.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_dev_data:/data/db
      - mongo_dev_data_config:/data/configdb
      - ./Service/Backend/seed.js:/docker-entrypoint-initdb.d/seed.js
    restart: always

  mongo-express:
    image: mongo-express:1.0.2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081

  frontend:
    image: crm-frontend-dev:1.0.0
    build:
      context: ./Service/Frontend
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env.frontend
    environment:
      VITE_API_URL: ${DEV_URL}:${BACKEND_PORT}
      VITE_WS_URL: ${WS_URL}:${BACKEND_PORT}
    volumes:
      - ./Service/Frontend/src:/app/src
    restart: always
    ports:
      - ${FRONTEND_PORT}:8000

volumes:
  mongo_dev_data:
  mongo_dev_data_config:
