services:
  backend:
    image: crm-backend:1.0.0
    build: ./Service/Backend
    env_file:
      - .env.backend
    environment:
      - MODE=Production
      - API_URL=${PROD_URL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./Log:/logs
    depends_on:
      - mongo
    ports:
      - ${BACKEND_PORT}:5000
    restart: always

  mongo:
    image: mongo:7.0.7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_data_config:/data/configdb
      - ./Service/Backend/seed.js:/docker-entrypoint-initdb.d/seed.js
    restart: always

  frontend:
    image: crm-frontend:1.0.0
    build: ./Service/Frontend
    env_file:
      - .env.frontend
    environment:
      VITE_API_URL: ${PROD_URL}
      VITE_WS_URL: ${WS_URL}:${BACKEND_PORT}

volumes:
  mongo_data:
  mongo_data_config:
